version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      cassandra:
        condition: service_healthy

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    healthcheck:
      test: [ "CMD-SHELL", "cqlsh -e 'describe cluster'" ]
      interval: 30s
      timeout: 10s
      retries: 3

  sample-data:
    image: cassandra:latest
    depends_on:
      cassandra:
        condition: service_healthy
    restart: "no"
    entrypoint: ["/create_cassandradb_keyspace.sh"]
    volumes:
      - ./create_cassandradb_keyspace.sh:/create_cassandradb_keyspace.sh