version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/dumplingscloud

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    healthcheck:
      test: [ "CMD-SHELL", "mongosh" ]
      interval: 20s
      timeout: 10s
      retries: 3